<?php

namespace CategoryBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LandRepository extends EntityRepository
{
}
