services:
  #    category.example:
  #        class: CategoryBundle\Example
  #        arguments: ["@service_id", "plain_value", "%parameter%"]

  category.admin.land:
    class: CategoryBundle\Admin\LandAdmin
    arguments: [~, CategoryBundle\Entity\Land, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Категория, label: Страна }

    category.admin.gender:
        class: CategoryBundle\Admin\GenderAdmin
        arguments: [~, CategoryBundle\Entity\Gender, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Gender }
