<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Sonata\UserBundle\Entity\BaseGroup as BaseGroup;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( https://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Group extends BaseGroup
{
    /**
     * @var integer $id
     */
    protected $id;

//    protected $categories;

    public function __construct($name, $roles = array())
    {
        $categories = array();

//        $this->categories = $categories;
        $this->name = $name;
        $this->roles = $roles;
    }


    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }



    /**
     * @param string $categories
     *
     * @return Group
     */
    public function addCategories($categories)
    {
        if (!$this->hasCategories($categories)) {
            $this->categories[] = $categories;
        }

        return $this;
    }


    /**
     * @param string $categories
     */
    public function hasCategories($categories)
    {
        return in_array($categories, $this->categories, true);
    }

    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * @param string $categories
     *
     * @return Group
     */
    public function removeCategories($categories)
    {
        if (false !== $key = array_search($categories, $this->categories, true)) {
            unset($this->categories[$key]);
            $this->categories = array_values($this->categories);
        }

        return $this;
    }


    /**
     * @param array $categories
     *
     * @return Group
     */
    public function setCategories(array $categories)
    {
        $this->categories = $categories;

        return $this;
    }
}