<?php

namespace Application\Sonata\MediaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Session\Session;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
    public function getById($id)
    {
        $sesion = new Session();
        $locale=$sesion->get("locale");
        return $this->createQueryBuilder('a')
//            ->select('a.id, a.url, a.title'.ucfirst($locale).' as title, photo.id as photo_url')
            ->select('a.id, a.name, a.providerName, a.providerReference')
            ->where('a.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
